---
- name: Install Nexus 3
  hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      pkg:
      - mc
      - nano
      - openjdk-11-jre
      state: present
  - name: Group 'nexus'
    group:
      name: nexus
      state: present
  - name: Add user 'nexus'
    user:
      name: nexus
      uid: 1050
      shell: /bin/bash
      create_home: yes
      home: /opt/nexus
      group: nexus
      comment: Nexus Server
  - name: Directory /opt/nexus
    file:
      path: /opt/nexus
      state: directory
      mode: '0775'
      owner: nexus
      group: nexus
  - name: Download Nexus 3
    get-url:
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /opt/nexus/latest-unix.tar.gz
      mode: '0777'
  - name: Unarhive nexus
    unarhive:
      src: /opt/nexus/latest-unix.tar.gz
      dest: /opt/nexus
  - name: File - nexus.service
    file:
      path: /etc/systemd/system/nexus.service
      state: touch
      mode: '0644'
      owner: root
      group: root
  - name: Configure nexus.service
    blockinfile:
      path: /etc/systed/system/nexus.service
      block: |
        [Unit]
        Description=Nexus-server
        After=syslog.target network.target

        [Service]
        SuccessExitStatus=143
        WorkingDirectory=/opt/nexus
        User=nexus
        Group=nexus
        Restart=on-failure
        Restart=20 5
        ExecStart=/opt/nexus/nexus-3.20.1-01/bin/nexus

        [Install]
        WantedBy=multi-user.target
  - name: Reload daemon
    systemd:
      daemon_reload: yes
  - name: Enable nexus.service
    systemd:
      name: nexus
      ebabled: yes
  - name: Restart nexus.service
    systemd:
      state: restarted
      daemon_reload: yes
      name: nexus