# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vm|
    vm.memory = 1048
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = 'playbook.yaml'
    ansible.inventory_path = "inventory/hosts"
    ansible.become = true
  end

  config.vm.define "nexus" do |nexus|
    nexus.vm.hostname = "nexus.puppet"
    nexus.vm.network "private_network", ip: "172.31.100.10"
    
    nexus.vm.provider "virtualbox" do |vb|
      vb.name = "nexus"
    end
  end
end
